deploy:
  script:
    - npm install  # Install dependencies locally
    - echo "$SSH_PRIVATE_KEY" > /tmp/ssh_private_key && chmod 600 /tmp/ssh_private_key  # Store the SSH key securely
    - scp -i /tmp/ssh_private_key -r * ubuntu@$AWS_PUBLIC_IP:/home/ubuntu/hello-node/  # Copy files to the remote server
    - ssh -i /tmp/ssh_private_key ubuntu@$AWS_PUBLIC_IP "cd /home/ubuntu/hello-node && npm install && npm start &"  # Execute the start command remotely
