deploy:
  script:
    # 1. EC2 pe npm dependencies install karna
    - ssh -i $SSH_PRIVATE_KEY ubuntu@$AWS_PUBLIC_IP "cd /home/ubuntu/hello-node && npm install"
    
    # 2. Build folder ko EC2 instance pe copy karna
    - scp -i $SSH_PRIVATE_KEY -r ./* ubuntu@$AWS_PUBLIC_IP:/home/ubuntu/hello-node/
    
    # 3. EC2 pe application ko run karna
    - ssh -i $SSH_PRIVATE_KEY ubuntu@$AWS_PUBLIC_IP "cd /home/ubuntu/hello-node && nohup npm start &"
