stages:
  - deploy

deploy:
  stage: deploy
  script:
    - echo "Deploying application..."
    # Application ko build aur deploy karne ke commands
    - npm install  # agar Node.js application hai
    - npm run build
    # Deploy commands
  only:
    - main  # main branch push par hi run hoga