name: Docker Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        run: git clone $GITHUB_SERVER_URL/$GITHUB_REPOSITORY .

      - name: Docker Login
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker Image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/hello-world:latest .

      - name: Push Docker Image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/hello-world:latest

#      - name: Save SSH key
 #       run: |
  #        echo "${{ secrets.EC2_KEY }}" > ec2_key.pem
#          chmod 600 ec2_key.pem
#
 #     - name: Deploy to EC2 via SSH
  #      run: |
   ##        echo "✅ Connected to EC2"
     #       sudo apt-get install docker.io -y
      #      sudo docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
       #     sudo docker pull ${{ secrets.DOCKER_USERNAME }}/hello-world:latest
        #    sudo docker stop hello || true
         #   sudo docker rm hello || true
          #  sudo docker run -d --name hello -p 3000:3000 ${{ secrets.DOCKER_USERNAME }}/hello-world:latest
     #       echo "🚀 Deployed!"
     #     EOF
      #    exit

      #- name: Delete SSH key
       # run: rm -f ec2_key.pem
