name: Deploy Webservice

on:
  push:
    branches:
      - main

jobs:
  # ✅ Auto deploy to DEV
  deploy-dev:
    runs-on: glpl-dev-be
    steps:
      - uses: actions/checkout@v3
      - name: Deploy to DEV
        run: |
          echo "Deploying to DEV server..."
          # your deployment script

  # ✅ Manual approval for QA
  deploy-qa:
    needs: deploy-dev
    runs-on: glpl-qa-be
    environment:
      name: qa
    steps:
      - uses: actions/checkout@v3
      - name: Deploy to QA
        run: |
          echo "Deploying to QA server..."
          # your deployment script

  # ✅ Hotfix, PPD, Prod similar
  deploy-hotfix:
    needs: deploy-dev
    runs-on: glpl-hotfix-be
    environment:
      name: hotfix
    steps:
      - uses: actions/checkout@v3
      - run: echo "Deploying to HOTFIX server..."

  deploy-ppd:
    needs: deploy-dev
    runs-on: glpl-ppd-be
    environment:
      name: ppd
    steps:
      - uses: actions/checkout@v3
      - run: echo "Deploying to PPD server..."

  deploy-prod:
    needs: deploy-dev
    runs-on: glpl-prod-be
    environment:
      name: prod
    steps:
      - uses: actions/checkout@v3
      - run: echo "Deploying to PROD server..."
